### ISSUE TITLE
[B] Breaking Mob Spawners only gives Pig Spawners

### ISSUE THREAD

**Issue by 0xEviqnn** [0xEviqnn/Silky-Spawners#2]
# Basic Details:
---
Minecraft Forge Version: N/A
Silky Spawners Version: 1.1
Java Version: 8_211
Operating System: W10

# A description of the Bug
—-
Alledgedly, on the CurseForge page, a user reported that regardless of what mob spawner you break. You will get a Pig Spawner everytime.

This could be due to the NBT tags that Spawners have.

I will need to write a bunch of code later on to check the NBT tag and return that mobs value (and support modded mobs)

**Comment by Codetoil** [comment]
I fixed it, put only partially, it places with the info in creative mode, but it loses the info when placing it in survival mode.

**Comment by Codetoil** [comment]
It is only partially fixed

**Comment by Codetoil** [comment]
Fixed with commit. Thank me later.
