### ISSUE TITLE
[R] Add named spawners?

### ISSUE THREAD

**Issue by 0xEviqnn** [0xEviqnn/Silky-Spawners#5]
If possible, we might be able to implement a way to "name" spawners.
So when you break say a pig spawner, it gets renamed to "Pig Spawner" instead of "Mob Spawner" for everything.

This could be done easily and no need to add mod support by getting the direct NBT data.

**Comment by Codetoil** [comment]
Two limitation is that spawners in inventories previously won't get renamed, and the spawners do not get renamed to the language set on the client, instead manipulating the built-in name.
Otherwise works pretty well!
